[Unit]
Wants=
After=
Wants=network-online.target researka-fullraw-search.service
After=network-online.target researka-fullraw-search.service

[Service]
UnsetEnvironment=V5_MEMO_PORTFOLIO_FULL_RAW_CORPUS_SEARCH_URL
